name: secret file
on : 
   push
jobs:
  secret-job:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve secret
      env:
        super_secret: ${{ secrets.SUPERSECRET }}
      run:  |
        echo  "the secret is $super_secret"
